# Generated by Django 3.1.3 on 2021-07-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=30)),
                ('post_title', models.CharField(max_length=50)),
                ('post_content', models.TextField()),
                ('post_time', models.DateTimeField()),
            ],
        ),
    ]
