# Generated by Django 3.1.3 on 2021-08-03 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_user_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_time',
        ),
        migrations.AddField(
            model_name='post',
            name='post_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
