# Generated by Django 3.1.3 on 2021-08-08 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_likedblogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likedblogs',
            options={'verbose_name_plural': 'Liked Blogs'},
        ),
    ]
